# Generated by Django 3.2.6 on 2022-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField(max_length=3)),
                ('Role', models.CharField(max_length=50)),
                ('friendshare', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=100)),
                ('improve', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
    ]
